### Using Numpy

In [4]:
import numpy as np

### Creating Numpy Arrays

In [5]:
my_list = [1,2,3]

In [6]:
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

In [10]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace

In [20]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [23]:
# [0, 1)
np.random.rand(2)

array([0.84899793, 0.31845876])

In [24]:
np.random.rand(5, 5)

array([[0.39293475, 0.23099252, 0.34798088, 0.39213466, 0.85837519],
       [0.08036809, 0.61827609, 0.83886924, 0.14310258, 0.04127818],
       [0.05588389, 0.56175194, 0.6465528 , 0.05593958, 0.78125968],
       [0.34338097, 0.30305705, 0.57480675, 0.17341075, 0.93039822],
       [0.13750168, 0.88375498, 0.31038684, 0.32746348, 0.57076883]])

In [25]:
np.random.randn(2)

array([-0.47652395,  0.40340444])

In [26]:
np.random.rand(5, 5)

array([[0.10082444, 0.15799199, 0.97589021, 0.65360252, 0.13780165],
       [0.32868705, 0.3313057 , 0.20938318, 0.12136021, 0.90104325],
       [0.53851686, 0.12778802, 0.20567038, 0.66909663, 0.93788231],
       [0.79785729, 0.09726692, 0.23279426, 0.71943474, 0.24776413],
       [0.74397537, 0.5376926 , 0.78551398, 0.73753302, 0.64552757]])

In [27]:
np.random.randint(1, 100)

28

In [28]:
np.random.randint(1,100, 10)

array([26, 82, 71, 16, 31, 78,  8, 22, 72, 96])

### Array Attributes and Methods

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0, 50, 10)

In [32]:
ranarr

array([ 2, 26,  0, 45,  4, 32,  2, 38, 14, 26])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr 

array([ 2, 26,  0, 45,  4, 32,  2, 38, 14, 26])

In [39]:
ranarr.min()

0

In [41]:
ranarr.argmin()

2

In [42]:
ranarr.max()

45

In [43]:
ranarr.argmax()

3

### Attributes

In [44]:
arr.shape

(25,)

In [47]:
arr.reshape(25,1).shape

(25, 1)

In [48]:
arr.dtype

dtype('int32')

### Indexing and Selection

In [49]:
arr = np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[8]

8

In [52]:
arr[1:5]

array([1, 2, 3, 4])

In [53]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [54]:
arr[:5]

array([0, 1, 2, 3, 4])

### Broadcasting

In [55]:
arr[0:5] = 100

In [56]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [66]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [70]:
slice_arr[:] = -1
slice_arr

array([-1, -1, -1, -1, -1, -1])

In [72]:
arr

array([-1, -1, -1, -1, -1, -1,  6,  7,  8,  9, 10])

In [67]:
arr_copy = arr.copy()

In [71]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexing a 2D Array

In [73]:
arr_2d = np.array(([5,10,15], [20, 25, 30], [35, 40, 45]))

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[1]

array([20, 25, 30])

In [76]:
arr_2d[1, 2]

30

In [77]:
arr_2d[1][2]

30

In [78]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

### Selection / Filtering

In [79]:
arr = np.arange(1,11)

In [80]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [82]:
boolval = arr > 4

In [83]:
arr[boolval]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

### Operations

In [86]:
arr = np.arange(0, 10)

In [87]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [90]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [92]:
arr.dot(arr)

285

In [111]:
arr = np.arange(1, 10)

In [112]:
arr = arr.reshape(3,3)

In [113]:
arr2 = np.arange(1,4)

array([1, 2, 3])

In [114]:
arr.dot(arr2.reshape(3,1))

array([[14],
       [32],
       [50]])

In [115]:
1 / 0

ZeroDivisionError: division by zero

In [116]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667],
       [0.14285714, 0.125     , 0.11111111]])

In [117]:
arr = np.arange(0,11)

In [118]:
1 / arr

C:\Users\ruder\AppData\Local\Temp/ipykernel_7740/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [119]:
arr / arr

C:\Users\ruder\AppData\Local\Temp/ipykernel_7740/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [120]:
arr / 0

C:\Users\ruder\AppData\Local\Temp/ipykernel_7740/3942562399.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr / 0
C:\Users\ruder\AppData\Local\Temp/ipykernel_7740/3942562399.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [121]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [122]:
arr * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [123]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [124]:
# y = e^x
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [125]:
np.max(arr)

10

In [126]:
np.min(arr)

0

In [127]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [128]:
np.log(arr)

C:\Users\ruder\AppData\Local\Temp/ipykernel_7740/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])